//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 11:02:14 AM CET 
//


package com.tibco.xmlns.extarchetype.patterns;

import com.tibco.xmlns.archetype.generator.Archetype;
import com.tibco.xmlns.archetype.generator.ArchetypeGeneration;
import com.tibco.xmlns.archetype.generator.Archetypes;
import com.tibco.xmlns.archetype.generator.ArchetypesGeneration;
import com.tibco.xmlns.archetype.generator.Artifact;
import com.tibco.xmlns.archetype.generator.Artifacts;
import com.tibco.xmlns.archetype.generator.GAV;
import com.tibco.xmlns.archetype.generator.Goal;
import com.tibco.xmlns.archetype.generator.Goals;
import com.tibco.xmlns.archetype.generator.MavenOptions;
import com.tibco.xmlns.archetype.generator.Parameter;
import com.tibco.xmlns.archetype.generator.Parameters;
import com.tibco.xmlns.extarchetype.validation.CustomRule;
import com.tibco.xmlns.extarchetype.validation.DefaultRule;
import com.tibco.xmlns.extarchetype.validation.InfoRule;
import com.tibco.xmlns.extarchetype.validation.Properties;
import com.tibco.xmlns.extarchetype.validation.Property;
import com.tibco.xmlns.extarchetype.validation.ReferenceProperty;
import com.tibco.xmlns.extarchetype.validation.Rules;
import com.tibco.xmlns.extarchetype.validation.TokenRule;
import com.tibco.xmlns.extarchetype.validation.ValidationRules;
import com.tibco.xmlns.extarchetype.validation.WarningRule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.extarchetype.patterns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArchetypesGeneration_QNAME = new QName("http://www.tibco.com/xmlns/archetype/generator", "archetypesGeneration");
    private final static QName _ValidationRules_QNAME = new QName("http://www.tibco.com/xmlns/extarchetype/validation", "validationRules");
    private final static QName _Archetypes_QNAME = new QName("http://www.tibco.com/xmlns/extarchetype/patterns", "archetypes");
    private final static QName _PatternsDescriptor_QNAME = new QName("http://www.tibco.com/xmlns/extarchetype/patterns", "patterns-descriptor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.extarchetype.patterns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link ReferenceProperty }
     * 
     */
    public ReferenceProperty createReferenceProperty() {
        return new ReferenceProperty();
    }

    /**
     * Create an instance of {@link ValidationRules }
     * 
     */
    public ValidationRules createValidationRules() {
        return new ValidationRules();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link PatternArchetype }
     * 
     */
    public PatternArchetype createPatternArchetype() {
        return new PatternArchetype();
    }

    /**
     * Create an instance of {@link MavenOptions }
     * 
     */
    public MavenOptions createMavenOptions() {
        return new MavenOptions();
    }

    /**
     * Create an instance of {@link PatternComponents }
     * 
     */
    public PatternComponents createPatternComponents() {
        return new PatternComponents();
    }

    /**
     * Create an instance of {@link ArchetypeGeneration }
     * 
     */
    public ArchetypeGeneration createArchetypeGeneration() {
        return new ArchetypeGeneration();
    }

    /**
     * Create an instance of {@link CustomRule }
     * 
     */
    public CustomRule createCustomRule() {
        return new CustomRule();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ArchetypesGeneration }
     * 
     */
    public ArchetypesGeneration createArchetypesGeneration() {
        return new ArchetypesGeneration();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link Archetypes }
     * 
     */
    public Archetypes createArchetypes() {
        return new Archetypes();
    }

    /**
     * Create an instance of {@link Archetype }
     * 
     */
    public Archetype createArchetype() {
        return new Archetype();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link TokenRule }
     * 
     */
    public TokenRule createTokenRule() {
        return new TokenRule();
    }

    /**
     * Create an instance of {@link PatternComponent }
     * 
     */
    public PatternComponent createPatternComponent() {
        return new PatternComponent();
    }

    /**
     * Create an instance of {@link InfoRule }
     * 
     */
    public InfoRule createInfoRule() {
        return new InfoRule();
    }

    /**
     * Create an instance of {@link Artifacts }
     * 
     */
    public Artifacts createArtifacts() {
        return new Artifacts();
    }

    /**
     * Create an instance of {@link PatternsDescriptor }
     * 
     */
    public PatternsDescriptor createPatternsDescriptor() {
        return new PatternsDescriptor();
    }

    /**
     * Create an instance of {@link Pattern }
     * 
     */
    public Pattern createPattern() {
        return new Pattern();
    }

    /**
     * Create an instance of {@link PatternProperty }
     * 
     */
    public PatternProperty createPatternProperty() {
        return new PatternProperty();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link PatternProperties }
     * 
     */
    public PatternProperties createPatternProperties() {
        return new PatternProperties();
    }

    /**
     * Create an instance of {@link GAV }
     * 
     */
    public GAV createGAV() {
        return new GAV();
    }

    /**
     * Create an instance of {@link WarningRule }
     * 
     */
    public WarningRule createWarningRule() {
        return new WarningRule();
    }

    /**
     * Create an instance of {@link DefaultRule }
     * 
     */
    public DefaultRule createDefaultRule() {
        return new DefaultRule();
    }

    /**
     * Create an instance of {@link Goals }
     * 
     */
    public Goals createGoals() {
        return new Goals();
    }

    /**
     * Create an instance of {@link PatternArchetypes }
     * 
     */
    public PatternArchetypes createPatternArchetypes() {
        return new PatternArchetypes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchetypesGeneration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/archetype/generator", name = "archetypesGeneration")
    public JAXBElement<ArchetypesGeneration> createArchetypesGeneration(ArchetypesGeneration value) {
        return new JAXBElement<ArchetypesGeneration>(_ArchetypesGeneration_QNAME, ArchetypesGeneration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationRules }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/extarchetype/validation", name = "validationRules")
    public JAXBElement<ValidationRules> createValidationRules(ValidationRules value) {
        return new JAXBElement<ValidationRules>(_ValidationRules_QNAME, ValidationRules.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Archetypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/extarchetype/patterns", name = "archetypes")
    public JAXBElement<Archetypes> createArchetypes(Archetypes value) {
        return new JAXBElement<Archetypes>(_Archetypes_QNAME, Archetypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternsDescriptor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/extarchetype/patterns", name = "patterns-descriptor")
    public JAXBElement<PatternsDescriptor> createPatternsDescriptor(PatternsDescriptor value) {
        return new JAXBElement<PatternsDescriptor>(_PatternsDescriptor_QNAME, PatternsDescriptor.class, null, value);
    }

}
