//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 11:02:14 AM CET 
//


package com.tibco.xmlns.extarchetype.patterns;

import com.tibco.xmlns.archetype.generator.GAV;
import com.tibco.xmlns.archetype.generator.Goals;
import com.tibco.xmlns.archetype.generator.MavenOptions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatternArchetype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatternArchetype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="archetypeGAV" type="{http://www.tibco.com/xmlns/archetype/generator}GAV"/>
 *         &lt;element name="goals" type="{http://www.tibco.com/xmlns/archetype/generator}Goals"/>
 *         &lt;element name="mavenOptions" type="{http://www.tibco.com/xmlns/archetype/generator}MavenOptions" minOccurs="0"/>
 *         &lt;element name="parameters" type="{http://www.tibco.com/xmlns/extarchetype/patterns}PatternProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatternArchetype", namespace = "http://www.tibco.com/xmlns/extarchetype/patterns", propOrder = {
    "name",
    "description",
    "archetypeGAV",
    "goals",
    "mavenOptions",
    "parameters"
})
@XmlSeeAlso({
    PatternComponent.class
})
public class PatternArchetype {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected GAV archetypeGAV;
    @XmlElement(required = true)
    protected Goals goals;
    protected MavenOptions mavenOptions;
    protected PatternProperties parameters;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the archetypeGAV property.
     * 
     * @return
     *     possible object is
     *     {@link GAV }
     *     
     */
    public GAV getArchetypeGAV() {
        return archetypeGAV;
    }

    /**
     * Sets the value of the archetypeGAV property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAV }
     *     
     */
    public void setArchetypeGAV(GAV value) {
        this.archetypeGAV = value;
    }

    /**
     * Gets the value of the goals property.
     * 
     * @return
     *     possible object is
     *     {@link Goals }
     *     
     */
    public Goals getGoals() {
        return goals;
    }

    /**
     * Sets the value of the goals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Goals }
     *     
     */
    public void setGoals(Goals value) {
        this.goals = value;
    }

    /**
     * Gets the value of the mavenOptions property.
     * 
     * @return
     *     possible object is
     *     {@link MavenOptions }
     *     
     */
    public MavenOptions getMavenOptions() {
        return mavenOptions;
    }

    /**
     * Sets the value of the mavenOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MavenOptions }
     *     
     */
    public void setMavenOptions(MavenOptions value) {
        this.mavenOptions = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link PatternProperties }
     *     
     */
    public PatternProperties getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatternProperties }
     *     
     */
    public void setParameters(PatternProperties value) {
        this.parameters = value;
    }

}
