//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 11:02:14 AM CET 
//


package com.tibco.xmlns.extarchetype.patterns;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatternArchetypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatternArchetypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="archetype" type="{http://www.tibco.com/xmlns/extarchetype/patterns}PatternArchetype" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatternArchetypes", namespace = "http://www.tibco.com/xmlns/extarchetype/patterns", propOrder = {
    "archetype"
})
public class PatternArchetypes {

    @XmlElement(required = true)
    protected List<PatternArchetype> archetype;

    /**
     * Gets the value of the archetype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archetype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchetype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatternArchetype }
     * 
     * 
     */
    public List<PatternArchetype> getArchetype() {
        if (archetype == null) {
            archetype = new ArrayList<PatternArchetype>();
        }
        return this.archetype;
    }

}
