# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: docker:latest
services:
- docker:dind
variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
  paths:
  - ".m2/repository/"
  - target/



stages:
- build
- package
- test
- visualize

maven-build:
  stage: build
  image: maven:3-jdk-11
  script:
  - mvn $MAVEN_CLI_OPTS clean initialize package install deploy
  artifacts:
    name: sonar-businessworks6-plugin-$CI_BUILD_ID-$CI_BUILD_REF
    expire_in: 1 day
    paths:
    - "./target"

sast:
  stage: test
  variables:
      SAST_EXCLUDED_PATHS: spec,test,tests,tmp,*target/site/jacoco/jacoco-resources/prettify.js*"
      SECURE_LOG_LEVEL: "debug"
include:
  - template: Security/SAST.gitlab-ci.yml



test-jdk11:
  stage: test
  image: maven:3.6.3-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml

coverage-jdk11:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or choose an existing stage like `deploy`.
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.9
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["test-jdk11"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml