//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 05:01:20 PM CET 
//


package com.tibco.xmlns.archetype.generator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArchetypeGeneration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArchetypeGeneration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/xmlns/archetype/generator}Artifact">
 *       &lt;sequence>
 *         &lt;element name="relativeProjectDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="goals" type="{http://www.tibco.com/xmlns/archetype/generator}Goals"/>
 *         &lt;element name="mavenOptions" type="{http://www.tibco.com/xmlns/archetype/generator}MavenOptions" minOccurs="0"/>
 *         &lt;element name="parameters" type="{http://www.tibco.com/xmlns/archetype/generator}Parameters" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArchetypeGeneration", propOrder = {
    "relativeProjectDir",
    "goals",
    "mavenOptions",
    "parameters"
})
public class ArchetypeGeneration
    extends Artifact
{

    @XmlElement(required = true)
    protected String relativeProjectDir;
    @XmlElement(required = true)
    protected Goals goals;
    protected MavenOptions mavenOptions;
    protected Parameters parameters;

    /**
     * Gets the value of the relativeProjectDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelativeProjectDir() {
        return relativeProjectDir;
    }

    /**
     * Sets the value of the relativeProjectDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelativeProjectDir(String value) {
        this.relativeProjectDir = value;
    }

    /**
     * Gets the value of the goals property.
     * 
     * @return
     *     possible object is
     *     {@link Goals }
     *     
     */
    public Goals getGoals() {
        return goals;
    }

    /**
     * Sets the value of the goals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Goals }
     *     
     */
    public void setGoals(Goals value) {
        this.goals = value;
    }

    /**
     * Gets the value of the mavenOptions property.
     * 
     * @return
     *     possible object is
     *     {@link MavenOptions }
     *     
     */
    public MavenOptions getMavenOptions() {
        return mavenOptions;
    }

    /**
     * Sets the value of the mavenOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MavenOptions }
     *     
     */
    public void setMavenOptions(MavenOptions value) {
        this.mavenOptions = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

}
