//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.07 at 05:01:20 PM CET 
//


package com.tibco.xmlns.archetype.generator;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.bwarchetype.template.generator package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArchetypesGeneration_QNAME = new QName("http://www.tibco.com/xmlns/archetype/generator", "archetypesGeneration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.bwarchetype.template.generator
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArchetypeGeneration }
     * 
     */
    public ArchetypeGeneration createArchetypeGeneration() {
        return new ArchetypeGeneration();
    }

    /**
     * Create an instance of {@link MavenOptions }
     * 
     */
    public MavenOptions createMavenOptions() {
        return new MavenOptions();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link GAV }
     * 
     */
    public GAV createGAV() {
        return new GAV();
    }

    /**
     * Create an instance of {@link Artifacts }
     * 
     */
    public Artifacts createArtifacts() {
        return new Artifacts();
    }

    /**
     * Create an instance of {@link Archetype }
     * 
     */
    public Archetype createArchetype() {
        return new Archetype();
    }

    /**
     * Create an instance of {@link Archetypes }
     * 
     */
    public Archetypes createArchetypes() {
        return new Archetypes();
    }

    /**
     * Create an instance of {@link Goals }
     * 
     */
    public Goals createGoals() {
        return new Goals();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link ArchetypesGeneration }
     * 
     */
    public ArchetypesGeneration createArchetypesGeneration() {
        return new ArchetypesGeneration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchetypesGeneration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/archetype/generator", name = "archetypesGeneration")
    public JAXBElement<ArchetypesGeneration> createArchetypesGeneration(ArchetypesGeneration value) {
        return new JAXBElement<ArchetypesGeneration>(_ArchetypesGeneration_QNAME, ArchetypesGeneration.class, null, value);
    }

}
