//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 07:15:40 PM CET 
//


package com.tibco.xmlns.extarchetype.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.tibco.xmlns.extarchetype.validation.ReferenceProperty;


/**
 * <p>Java class for ExtendedReferenceProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedReferenceProperty">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/xmlns/extarchetype/validation}ReferenceProperty">
 *       &lt;sequence>
 *         &lt;element name="source">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="deduction"/>
 *               &lt;enumeration value="input"/>
 *               &lt;enumeration value="global"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedReferenceProperty", namespace = "http://www.tibco.com/xmlns/extarchetype/metadata", propOrder = {
    "source"
})
public class ExtendedReferenceProperty
    extends ReferenceProperty
{

    @XmlElement(required = true)
    protected String source;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

}
