//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 07:15:40 PM CET 
//


package com.tibco.xmlns.extarchetype.metadata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.tibco.xmlns.extarchetype.validation.CustomRule;
import com.tibco.xmlns.extarchetype.validation.DefaultRule;
import com.tibco.xmlns.extarchetype.validation.InfoRule;
import com.tibco.xmlns.extarchetype.validation.Properties;
import com.tibco.xmlns.extarchetype.validation.Property;
import com.tibco.xmlns.extarchetype.validation.ReferenceProperty;
import com.tibco.xmlns.extarchetype.validation.Rules;
import com.tibco.xmlns.extarchetype.validation.TokenRule;
import com.tibco.xmlns.extarchetype.validation.ValidationRules;
import com.tibco.xmlns.extarchetype.validation.WarningRule;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.xmlns.extarchetype.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidationRules_QNAME = new QName("http://www.tibco.com/xmlns/extarchetype/validation", "validationRules");
    private final static QName _ExtarchetypeDescriptor_QNAME = new QName("http://www.tibco.com/xmlns/extarchetype/metadata", "extarchetype-descriptor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.xmlns.extarchetype.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfoRule }
     * 
     */
    public InfoRule createInfoRule() {
        return new InfoRule();
    }

    /**
     * Create an instance of {@link TokenRule }
     * 
     */
    public TokenRule createTokenRule() {
        return new TokenRule();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ReferenceProperty }
     * 
     */
    public ReferenceProperty createReferenceProperty() {
        return new ReferenceProperty();
    }

    /**
     * Create an instance of {@link ExtArchetypeDescriptor }
     * 
     */
    public ExtArchetypeDescriptor createExtArchetypeDescriptor() {
        return new ExtArchetypeDescriptor();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link ExtendedProperties }
     * 
     */
    public ExtendedProperties createExtendedProperties() {
        return new ExtendedProperties();
    }

    /**
     * Create an instance of {@link WarningRule }
     * 
     */
    public WarningRule createWarningRule() {
        return new WarningRule();
    }

    /**
     * Create an instance of {@link ExtendedReferenceProperty }
     * 
     */
    public ExtendedReferenceProperty createExtendedReferenceProperty() {
        return new ExtendedReferenceProperty();
    }

    /**
     * Create an instance of {@link ValidationRules }
     * 
     */
    public ValidationRules createValidationRules() {
        return new ValidationRules();
    }

    /**
     * Create an instance of {@link DefaultRule }
     * 
     */
    public DefaultRule createDefaultRule() {
        return new DefaultRule();
    }

    /**
     * Create an instance of {@link CustomRule }
     * 
     */
    public CustomRule createCustomRule() {
        return new CustomRule();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationRules }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/extarchetype/validation", name = "validationRules")
    public JAXBElement<ValidationRules> createValidationRules(ValidationRules value) {
        return new JAXBElement<ValidationRules>(_ValidationRules_QNAME, ValidationRules.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtArchetypeDescriptor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tibco.com/xmlns/extarchetype/metadata", name = "extarchetype-descriptor")
    public JAXBElement<ExtArchetypeDescriptor> createExtarchetypeDescriptor(ExtArchetypeDescriptor value) {
        return new JAXBElement<ExtArchetypeDescriptor>(_ExtarchetypeDescriptor_QNAME, ExtArchetypeDescriptor.class, null, value);
    }

}
