/*
 * Copyright (C) 2016-2020. TIBCO Software Inc. All Rights Reserved. Confidential & Proprietary.
 */
package com.tibco.sonar.plugins.bw6.check.process;

import com.tibco.sonar.plugins.bw6.source.ProcessSource;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.AfterClass;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyInt;
import static org.mockito.Matchers.anyString;
import org.mockito.Mockito;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.times;
import org.sonar.api.internal.apachecommons.io.FileUtils;

/**
 *
 * @author avazquez
 */
public class UnneededGroupCheckTest {

    public UnneededGroupCheckTest() {
    }

    private static ProcessSource source;

    @BeforeClass
    public static void setUpClass() {

        source = new ProcessSource("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<bpws:process exitOnStandardFault=\"no\" name=\"t1.module.Process\"\n"
                + "    suppressJoinFailure=\"yes\"\n"
                + "    targetNamespace=\"http://xmlns.example.com/20190719152314\"\n"
                + "    xmlns:bpws=\"http://docs.oasis-open.org/wsbpel/2.0/process/executable\"\n"
                + "    xmlns:info=\"http://www.tibco.com/bw/process/info\"\n"
                + "    xmlns:ns=\"http://www.tibco.com/pe/EngineTypes\"\n"
                + "    xmlns:ns0=\"http://tns.tibco.com/bw/activity/timer/xsd/output\"\n"
                + "    xmlns:ns1=\"http://www.tibco.com/pe/WriteToLogActivitySchema\"\n"
                + "    xmlns:sca=\"http://docs.oasis-open.org/ns/opencsa/sca/200912\"\n"
                + "    xmlns:sca-bpel=\"http://docs.oasis-open.org/ns/opencsa/sca-bpel/200801\"\n"
                + "    xmlns:tibex=\"http://www.tibco.com/bpel/2007/extensions\"\n"
                + "    xmlns:tibprop=\"http://ns.tibco.com/bw/property\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n"
                + "    <tibex:Types>\n"
                + "        <xs:schema attributeFormDefault=\"unqualified\"\n"
                + "            elementFormDefault=\"qualified\"\n"
                + "            targetNamespace=\"http://www.tibco.com/pe/EngineTypes\"\n"
                + "            xmlns:tns=\"http://www.tibco.com/pe/EngineTypes\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
                + "            <xs:complexType block=\"extension restriction\"\n"
                + "                final=\"extension restriction\" name=\"ErrorReport\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"StackTrace\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"Msg\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"FullClass\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"Class\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"ProcessStack\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"MsgCode\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"Data\" type=\"tns:anydata\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:complexType block=\"extension restriction\"\n"
                + "                final=\"extension restriction\" name=\"OptionalErrorReport\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"StackTrace\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"Msg\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"FullClass\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"Class\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"ProcessStack\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"MsgCode\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"Data\" type=\"tns:anydata\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:complexType block=\"extension restriction\"\n"
                + "                final=\"extension restriction\" name=\"FaultDetail\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"ActivityName\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\" name=\"Data\" type=\"tns:anydata\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"Msg\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"MsgCode\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"ProcessStack\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"StackTrace\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"FullClass\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"Class\" type=\"xs:string\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:complexType block=\"extension restriction\"\n"
                + "                final=\"extension restriction\" name=\"ProcessContext\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"JobId\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"ApplicationName\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"EngineName\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" name=\"ProcessInstanceId\" type=\"xs:string\"/>\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"CustomJobId\" type=\"xs:string\"/>\n"
                + "                    <!--xs:element name=\"RestartedFromCheckpoint\" form=\"unqualified\" block=\"extension restriction substitution\" type=\"xs:boolean\"/-->\n"
                + "                    <xs:element\n"
                + "                        block=\"extension restriction substitution\"\n"
                + "                        form=\"unqualified\" maxOccurs=\"unbounded\"\n"
                + "                        minOccurs=\"0\" name=\"TrackingInfo\" type=\"xs:string\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:complexType block=\"extension restriction\"\n"
                + "                final=\"extension restriction\" name=\"anydata\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:any namespace=\"##any\" processContents=\"lax\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:element block=\"extension restriction substitution\"\n"
                + "                final=\"extension restriction\" name=\"OptionalErrorReport\" type=\"tns:OptionalErrorReport\"/>\n"
                + "            <xs:element block=\"extension restriction substitution\"\n"
                + "                final=\"extension restriction\" name=\"ErrorReport\" type=\"tns:ErrorReport\"/>\n"
                + "            <xs:element block=\"extension restriction substitution\"\n"
                + "                final=\"extension restriction\" name=\"FaultDetail\" type=\"tns:FaultDetail\"/>\n"
                + "            <xs:element block=\"extension restriction substitution\"\n"
                + "                final=\"extension restriction\" name=\"ProcessContext\" type=\"tns:ProcessContext\"/>\n"
                + "            <xs:element block=\"extension restriction substitution\"\n"
                + "                final=\"extension restriction\" name=\"CorrelationValue\" type=\"xs:string\"/>\n"
                + "        </xs:schema>\n"
                + "        <schema attributeFormDefault=\"unqualified\"\n"
                + "            elementFormDefault=\"unqualified\"\n"
                + "            targetNamespace=\"http://schemas.tibco.com/bw/pe/plugin/5.0/exceptions\"\n"
                + "            version=\"\" xmlns=\"http://www.w3.org/2001/XMLSchema\" xmlns:tns=\"http://schemas.tibco.com/bw/pe/plugin/5.0/exceptions\">\n"
                + "            <complexType name=\"ActivityExceptionType\">\n"
                + "                <sequence>\n"
                + "                    <element name=\"msg\" type=\"string\"/>\n"
                + "                    <element minOccurs=\"0\" name=\"msgCode\" type=\"string\"/>\n"
                + "                </sequence>\n"
                + "            </complexType>\n"
                + "            <element name=\"ActivityException\" type=\"tns:ActivityExceptionType\"/>\n"
                + "            <complexType name=\"ActivityTimedOutExceptionType\">\n"
                + "                <complexContent>\n"
                + "                    <extension base=\"tns:ActivityExceptionType\"/>\n"
                + "                </complexContent>\n"
                + "            </complexType>\n"
                + "            <element name=\"ActivityTimedOutException\" type=\"tns:ActivityTimedOutExceptionType\"/>\n"
                + "            <complexType name=\"DuplicateKeyExceptionType\">\n"
                + "                <complexContent>\n"
                + "                    <extension base=\"tns:ActivityExceptionType\">\n"
                + "                        <sequence>\n"
                + "                            <element name=\"duplicateKey\" type=\"string\"/>\n"
                + "                            <element minOccurs=\"0\" name=\"previousJobID\" type=\"string\"/>\n"
                + "                        </sequence>\n"
                + "                    </extension>\n"
                + "                </complexContent>\n"
                + "            </complexType>\n"
                + "            <element name=\"DuplicateKeyException\" type=\"tns:DuplicateKeyExceptionType\"/>\n"
                + "        </schema>\n"
                + "        <xs:schema attributeFormDefault=\"unqualified\"\n"
                + "            elementFormDefault=\"qualified\"\n"
                + "            targetNamespace=\"http://tns.tibco.com/bw/activity/timer/xsd/output\"\n"
                + "            xmlns:tns=\"http://tns.tibco.com/bw/activity/timer/xsd/output\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
                + "            <xs:complexType name=\"TimerOutputSchemaType\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Now\" type=\"xs:long\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Hour\" type=\"xs:int\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Minute\" type=\"xs:int\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Second\" type=\"xs:int\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Week\" type=\"xs:int\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Month\" type=\"xs:int\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Year\" type=\"xs:int\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Date\" type=\"xs:date\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"Time\" type=\"xs:string\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"DayOfMonth\" type=\"xs:int\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:element name=\"TimerOutputSchema\" type=\"tns:TimerOutputSchemaType\"/>\n"
                + "        </xs:schema>\n"
                + "        <xs:schema attributeFormDefault=\"unqualified\"\n"
                + "            elementFormDefault=\"qualified\"\n"
                + "            targetNamespace=\"http://www.tibco.com/pe/WriteToLogActivitySchema\"\n"
                + "            xmlns:tns=\"http://www.tibco.com/pe/WriteToLogActivitySchema\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n"
                + "            <xs:complexType name=\"LogParametersType\">\n"
                + "                <xs:sequence>\n"
                + "                    <xs:element form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"msgCode\" type=\"xs:string\"/>\n"
                + "                    <xs:element form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"loggerName\" type=\"xs:string\"/>\n"
                + "                    <xs:element form=\"unqualified\" minOccurs=\"0\"\n"
                + "                        name=\"logLevel\" type=\"xs:string\"/>\n"
                + "                    <xs:element form=\"unqualified\" name=\"message\" type=\"xs:string\"/>\n"
                + "                </xs:sequence>\n"
                + "            </xs:complexType>\n"
                + "            <xs:element name=\"ActivityInput\" type=\"tns:LogParametersType\"/>\n"
                + "        </xs:schema>\n"
                + "    </tibex:Types>\n"
                + "    <tibex:ProcessInfo callable=\"false\" createdBy=\"avazquez\"\n"
                + "        createdOn=\"Fri Jul 19 15:23:14 CEST 2019\" description=\"\"\n"
                + "        extraErrorVars=\"true\" modifiers=\"public\"\n"
                + "        productVersion=\"6.5.1 V9 2019-02-06\" scalable=\"true\"\n"
                + "        singleton=\"true\" stateless=\"false\" type=\"IT\"/>\n"
                + "    <tibex:ProcessInterface context=\"\" input=\"\" output=\"\"/>\n"
                + "    <tibex:ProcessTemplateConfigurations/>\n"
                + "    <notation:Diagram measurementUnit=\"Pixel\" type=\"BWProcess\"\n"
                + "        xmlns:bwnotation=\"http://tns.tibco.com/bw/runtime/BWNotation\"\n"
                + "        xmlns:notation=\"http://www.eclipse.org/gmf/runtime/1.0.2/notation\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
                + "        <children type=\"2001\">\n"
                + "            <children type=\"5001\"/>\n"
                + "            <children type=\"3001\">\n"
                + "                <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                <element href=\"//0/@process\"/>\n"
                + "            </children>\n"
                + "            <children type=\"3002\">\n"
                + "                <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "            </children>\n"
                + "            <children type=\"3003\">\n"
                + "                <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "            </children>\n"
                + "            <children type=\"3004\">\n"
                + "                <children type=\"4018\">\n"
                + "                    <children type=\"3018\">\n"
                + "                        <children type=\"4020\">\n"
                + "                            <children type=\"3020\">\n"
                + "                                <children type=\"4005\">\n"
                + "                                    <children type=\"3007\">\n"
                + "                                    <children type=\"4002 bw.generalactivities.timer\">\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.0\"/>\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"40\" width=\"40\"\n"
                + "                                    x=\"-10\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"98\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4018\">\n"
                + "                                    <children type=\"3018\">\n"
                + "                                    <children type=\"4020\">\n"
                + "                                    <children type=\"3020\">\n"
                + "                                    <children type=\"4005\">\n"
                + "                                    <children type=\"3007\">\n"
                + "\n"
                + "                                    <children type=\"4018\">\n"
                + "\n"
                + "                                    <children type=\"3018\">\n"
                + "\n"
                + "                                    <children type=\"4020\">\n"
                + "\n"
                + "                                    <children type=\"3020\">\n"
                + "\n"
                + "                                    <children type=\"4005\">\n"
                + "\n"
                + "                                    <children type=\"3007\">\n"
                + "\n"
                + "                                    <children type=\"4002\">\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2/@activity/@activities.1/@activity/@activity/@activities.2\"/>\n"
                + "\n"
                + "                                    <layoutConstraint\n"
                + "                                    x=\"19\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"31\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:DrawerStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2/@activity/@activities.1/@activity/@activity\"/>\n"
                + "\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"108\"\n"
                + "                                    width=\"400\"\n"
                + "                                    x=\"2\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"2\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2\"/>\n"
                + "\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"320\"\n"
                + "                                    width=\"420\"\n"
                + "                                    x=\"30\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"20\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4002\">\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2/@activity/@activities.1/@activity/@activity/@activities.0\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4002\">\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <children type=\"4017\">\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2/@activity/@activities.1/@activity/@activity/@activities.1\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    </children>\n"
                + "\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2\"/>\n"
                + "\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"165\"\n"
                + "                                    width=\"213\"\n"
                + "                                    x=\"25\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"20\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles xsi:type=\"notation:DrawerStyle\"/>\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity\"/>\n"
                + "\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"108\"\n"
                + "                                    width=\"400\"\n"
                + "                                    x=\"2\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"2\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1\"/>\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"320\"\n"
                + "                                    width=\"420\"\n"
                + "                                    x=\"30\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"20\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4002\">\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.0\"/>\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4002\">\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <children type=\"4017\">\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles\n"
                + "                                    fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles\n"
                + "                                    backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.1\"/>\n"
                + "                                    <layoutConstraint xsi:type=\"notation:Bounds\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity/@activities.1\"/>\n"
                + "                                    <layoutConstraint\n"
                + "                                    height=\"255\" width=\"303\"\n"
                + "                                    x=\"76\"\n"
                + "                                    xsi:type=\"notation:Bounds\" y=\"5\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles xsi:type=\"notation:DrawerStyle\"/>\n"
                + "                                    <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                                    <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity\"/>\n"
                + "                                    </children>\n"
                + "                                    <styles fontName=\"Segoe UI\"\n"
                + "                                    lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                                    <styles backgroundColor=\"16777215\"\n"
                + "                                    gradientEndColor=\"50431\"\n"
                + "                                    gradientStartColor=\"16777215\" xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "                                    <element href=\"//0/@process/@activity/@activity\"/>\n"
                + "                                    <layoutConstraint height=\"384\"\n"
                + "                                    width=\"515\" xsi:type=\"notation:Bounds\"/>\n"
                + "                                </children>\n"
                + "                                <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                                <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                            </children>\n"
                + "                            <styles fontName=\"Segoe UI\" lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                            <styles xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                            <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "                            <element href=\"//0/@process/@activity\"/>\n"
                + "                            <layoutConstraint height=\"365\" width=\"444\"\n"
                + "                                x=\"30\" xsi:type=\"notation:Bounds\" y=\"20\"/>\n"
                + "                        </children>\n"
                + "                        <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                        <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                        <element href=\"//0/@process/@activity\"/>\n"
                + "                    </children>\n"
                + "                    <styles fontName=\"Segoe UI\" lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "                    <styles xsi:type=\"bwnotation:BackgroundStyle\"/>\n"
                + "                    <styles xsi:type=\"bwnotation:ResizingStyle\"/>\n"
                + "                    <element href=\"//0/@process/@activity\"/>\n"
                + "                    <layoutConstraint height=\"409\" width=\"519\" xsi:type=\"notation:Bounds\"/>\n"
                + "                </children>\n"
                + "                <styles xsi:type=\"notation:SortingStyle\"/>\n"
                + "                <styles xsi:type=\"notation:FilteringStyle\"/>\n"
                + "                <element href=\"//0/@process\"/>\n"
                + "            </children>\n"
                + "            <styles fontName=\"Segoe UI\" lineColor=\"0\" xsi:type=\"notation:ShapeStyle\"/>\n"
                + "            <element href=\"//0/@process\"/>\n"
                + "            <layoutConstraint height=\"460\" width=\"860\" xsi:type=\"notation:Bounds\"/>\n"
                + "        </children>\n"
                + "        <styles xsi:type=\"notation:DiagramStyle\"/>\n"
                + "        <element href=\"//0\"/>\n"
                + "        <edges\n"
                + "            source=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0\"\n"
                + "            target=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1\" type=\"4006\">\n"
                + "            <children type=\"6002\">\n"
                + "                <layoutConstraint xsi:type=\"notation:Location\" y=\"40\"/>\n"
                + "            </children>\n"
                + "            <styles lineColor=\"0\" xsi:type=\"notation:ConnectorStyle\"/>\n"
                + "            <styles fontName=\"Segoe UI\" xsi:type=\"notation:FontStyle\"/>\n"
                + "            <element href=\"//0/@process/@activity/@activity/@links/@children.0\"/>\n"
                + "            <bendpoints points=\"[0, 0, 0, 0]$[0, 0, 0, 0]\" xsi:type=\"notation:RelativeBendpoints\"/>\n"
                + "        </edges>\n"
                + "        <edges\n"
                + "            source=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1\"\n"
                + "            target=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0\" type=\"4006\">\n"
                + "            <children type=\"6002\">\n"
                + "                <layoutConstraint xsi:type=\"notation:Location\" y=\"40\"/>\n"
                + "            </children>\n"
                + "            <styles lineColor=\"0\" xsi:type=\"notation:ConnectorStyle\"/>\n"
                + "            <styles fontName=\"Segoe UI\" xsi:type=\"notation:FontStyle\"/>\n"
                + "            <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2/@activity/@activities.1/@activity/@activity/@links/@children.0\"/>\n"
                + "            <bendpoints points=\"[0, 0, 0, 0]$[0, 0, 0, 0]\" xsi:type=\"notation:RelativeBendpoints\"/>\n"
                + "        </edges>\n"
                + "        <edges\n"
                + "            source=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0\"\n"
                + "            target=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.2\" type=\"4006\">\n"
                + "            <children type=\"6002\">\n"
                + "                <layoutConstraint xsi:type=\"notation:Location\" y=\"40\"/>\n"
                + "            </children>\n"
                + "            <styles lineColor=\"0\" xsi:type=\"notation:ConnectorStyle\"/>\n"
                + "            <styles fontName=\"Segoe UI\" xsi:type=\"notation:FontStyle\"/>\n"
                + "            <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@activities.2/@activity/@activities.1/@activity/@activity/@links/@children.1\"/>\n"
                + "            <bendpoints points=\"[0, 0, 0, 0]$[0, 0, 0, 0]\" xsi:type=\"notation:RelativeBendpoints\"/>\n"
                + "        </edges>\n"
                + "        <edges\n"
                + "            source=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.1\"\n"
                + "            target=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0\" type=\"4006\">\n"
                + "            <children type=\"6002\">\n"
                + "                <layoutConstraint xsi:type=\"notation:Location\" y=\"40\"/>\n"
                + "            </children>\n"
                + "            <styles lineColor=\"0\" xsi:type=\"notation:ConnectorStyle\"/>\n"
                + "            <styles fontName=\"Segoe UI\" xsi:type=\"notation:FontStyle\"/>\n"
                + "            <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@links/@children.0\"/>\n"
                + "            <bendpoints points=\"[0, 0, 0, 0]$[0, 0, 0, 0]\" xsi:type=\"notation:RelativeBendpoints\"/>\n"
                + "        </edges>\n"
                + "        <edges\n"
                + "            source=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0\"\n"
                + "            target=\"//@children.0/@children.4/@children.0/@children.0/@children.0/@children.0/@children.0/@children.0/@children.1/@children.0/@children.2\" type=\"4006\">\n"
                + "            <children type=\"6002\">\n"
                + "                <layoutConstraint xsi:type=\"notation:Location\" y=\"40\"/>\n"
                + "            </children>\n"
                + "            <styles lineColor=\"0\" xsi:type=\"notation:ConnectorStyle\"/>\n"
                + "            <styles fontName=\"Segoe UI\" xsi:type=\"notation:FontStyle\"/>\n"
                + "            <element href=\"//0/@process/@activity/@activity/@activities.1/@activity/@activities.1/@activity/@activity/@links/@children.1\"/>\n"
                + "            <bendpoints points=\"[0, 0, 0, 0]$[0, 0, 0, 0]\" xsi:type=\"notation:RelativeBendpoints\"/>\n"
                + "        </edges>\n"
                + "    </notation:Diagram>\n"
                + "    <bpws:variables>\n"
                + "        <bpws:variable element=\"ns:ProcessContext\"\n"
                + "            name=\"_processContext\" sca-bpel:internal=\"true\"/>\n"
                + "        <bpws:variable element=\"ns0:TimerOutputSchema\" name=\"Timer\" sca-bpel:internal=\"true\"/>\n"
                + "        <bpws:variable element=\"ns1:ActivityInput\" name=\"Log-input\" sca-bpel:internal=\"true\"/>\n"
                + "    </bpws:variables>\n"
                + "    <bpws:extensions>\n"
                + "        <bpws:extension mustUnderstand=\"no\" namespace=\"http://www.eclipse.org/gmf/runtime/1.0.2/notation\"/>\n"
                + "        <bpws:extension mustUnderstand=\"no\" namespace=\"http://www.tibco.com/bw/process/info\"/>\n"
                + "        <bpws:extension mustUnderstand=\"no\" namespace=\"http://docs.oasis-open.org/ns/opencsa/sca-bpel/200801\"/>\n"
                + "        <bpws:extension mustUnderstand=\"no\" namespace=\"http://docs.oasis-open.org/ns/opencsa/sca/200912\"/>\n"
                + "        <bpws:extension mustUnderstand=\"no\" namespace=\"http://ns.tibco.com/bw/property\"/>\n"
                + "        <bpws:extension mustUnderstand=\"no\" namespace=\"http://www.tibco.com/bpel/2007/extensions\"/>\n"
                + "    </bpws:extensions>\n"
                + "    <bpws:scope name=\"scope\">\n"
                + "        <bpws:flow name=\"flow\">\n"
                + "            <bpws:links>\n"
                + "                <bpws:link name=\"TimerToIterate1\" tibex:linkType=\"SUCCESS\"/>\n"
                + "            </bpws:links>\n"
                + "            <bpws:extensionActivity>\n"
                + "                <tibex:receiveEvent createInstance=\"yes\"\n"
                + "                    eventTimeout=\"60\" name=\"Timer\"\n"
                + "                    tibex:xpdlId=\"40d46caf-83a3-40c0-af73-5f50e5d92c3f\"\n"
                + "                    variable=\"Timer\" xmlns:tibex=\"http://www.tibco.com/bpel/2007/extensions\">\n"
                + "                    <bpws:sources>\n"
                + "                        <bpws:source linkName=\"TimerToIterate1\"/>\n"
                + "                    </bpws:sources>\n"
                + "                    <tibex:eventSource>\n"
                + "                        <bwext:BWActivity\n"
                + "                            activityTypeID=\"bw.generalactivities.timer\"\n"
                + "                            version=\"6.0.0.001\"\n"
                + "                            xmlns:activityconfig=\"http://tns.tibco.com/bw/model/activityconfig\"\n"
                + "                            xmlns:bwext=\"http://tns.tibco.com/bw/model/core/bwext\"\n"
                + "                            xmlns:generalactivities=\"http://ns.tibco.com/bw/palette/generalactivities\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
                + "                            <activityConfig>\n"
                + "                                <properties name=\"config\" xsi:type=\"activityconfig:EMFProperty\">\n"
                + "                                    <type href=\"http://ns.tibco.com/bw/palette/generalactivities#//Timer\"/>\n"
                + "                                    <value\n"
                + "                                    endTime=\"2019-07-19T15:24:44.432+0200\"\n"
                + "                                    intervalUnit=\"Second\"\n"
                + "                                    runOnce=\"true\"\n"
                + "                                    startTime=\"2019-07-19T15:24:44.432+0200\"\n"
                + "                                    timeInterval=\"1\" xsi:type=\"generalactivities:Timer\"/>\n"
                + "                                </properties>\n"
                + "                            </activityConfig>\n"
                + "                        </bwext:BWActivity>\n"
                + "                    </tibex:eventSource>\n"
                + "                </tibex:receiveEvent>\n"
                + "            </bpws:extensionActivity>\n"
                + "            <bpws:scope name=\"Iterate1\" tibex:group=\"iterate\"\n"
                + "                tibex:indexOriginalName=\"index1\"\n"
                + "                tibex:indexToGlobal=\"false\" tibex:xpdlId=\"efc18eb5-1c1c-454d-8c16-edf625ca65b9\">\n"
                + "                <bpws:targets>\n"
                + "                    <bpws:target linkName=\"TimerToIterate1\"/>\n"
                + "                </bpws:targets>\n"
                + "                <bpws:sequence name=\"sequence1\" tibex:group=\"iterate\">\n"
                + "                    <bpws:empty name=\"GroupInit1\" tibex:group=\"groupInit\"/>\n"
                + "                    <bpws:forEach counterName=\"index1\" name=\"iterate1\"\n"
                + "                        parallel=\"no\" tibex:group=\"iterate\">\n"
                + "                        <bpws:startCounterValue><![CDATA[1]]></bpws:startCounterValue>\n"
                + "                        <bpws:finalCounterValue><![CDATA[1]]></bpws:finalCounterValue>\n"
                + "                        <bpws:scope name=\"innerScope1\">\n"
                + "                            <bpws:variables>\n"
                + "                                <bpws:variable name=\"currentElement\" sca-bpel:internal=\"true\"/>\n"
                + "                            </bpws:variables>\n"
                + "                            <bpws:flow name=\"flow2\">\n"
                + "                                <bpws:links>\n"
                + "                                    <bpws:link\n"
                + "                                    name=\"GroupStart1ToIterate\" tibex:linkType=\"SUCCESS\"/>\n"
                + "                                    <bpws:link name=\"IterateToGroupEnd1\" tibex:linkType=\"SUCCESS\"/>\n"
                + "                                </bpws:links>\n"
                + "                                <bpws:assign name=\"GroupStart1\"\n"
                + "                                    tibex:group=\"groupStart\"\n"
                + "                                    tibex:xpdlId=\"3d990a79-ae8c-4163-afb7-44f58cb20241\" validate=\"no\">\n"
                + "                                    <bpws:sources>\n"
                + "                                    <bpws:source linkName=\"GroupStart1ToIterate\"/>\n"
                + "                                    </bpws:sources>\n"
                + "                                    <bpws:copy>\n"
                + "                                    <bpws:from expressionLanguage=\"urn:oasis:names:tc:wsbpel:2.0:sublang:xpath2.0\"/>\n"
                + "                                    <bpws:to variable=\"currentElement\"/>\n"
                + "                                    </bpws:copy>\n"
                + "                                </bpws:assign>\n"
                + "                                <bpws:empty name=\"GroupEnd1\"\n"
                + "                                    tibex:group=\"groupEnd\" tibex:xpdlId=\"051ac023-4669-4c36-9019-bb6f82743a13\">\n"
                + "                                    <bpws:targets>\n"
                + "                                    <bpws:target linkName=\"IterateToGroupEnd1\"/>\n"
                + "                                    </bpws:targets>\n"
                + "                                </bpws:empty>\n"
                + "                                <bpws:scope name=\"Iterate\"\n"
                + "                                    tibex:group=\"iterate\"\n"
                + "                                    tibex:indexOriginalName=\"index\"\n"
                + "                                    tibex:indexToGlobal=\"false\" tibex:xpdlId=\"e6ef95ed-d285-4dc3-9f13-80966bf1c28c\">\n"
                + "                                    <bpws:targets>\n"
                + "                                    <bpws:target linkName=\"GroupStart1ToIterate\"/>\n"
                + "                                    </bpws:targets>\n"
                + "                                    <bpws:sources>\n"
                + "                                    <bpws:source linkName=\"IterateToGroupEnd1\"/>\n"
                + "                                    </bpws:sources>\n"
                + "                                    <bpws:sequence name=\"sequence\" tibex:group=\"iterate\">\n"
                + "                                    <bpws:empty name=\"GroupInit\" tibex:group=\"groupInit\"/>\n"
                + "                                    <bpws:forEach\n"
                + "                                    counterName=\"index\"\n"
                + "                                    name=\"iterate\" parallel=\"no\" tibex:group=\"iterate\">\n"
                + "                                    <bpws:startCounterValue><![CDATA[1]]></bpws:startCounterValue>\n"
                + "                                    <bpws:finalCounterValue><![CDATA[1]]></bpws:finalCounterValue>\n"
                + "                                    <bpws:scope name=\"innerScope\">\n"
                + "                                    <bpws:variables>\n"
                + "                                    <bpws:variable\n"
                + "                                    name=\"currentElement\" sca-bpel:internal=\"true\"/>\n"
                + "                                    </bpws:variables>\n"
                + "                                    <bpws:flow name=\"flow1\">\n"
                + "                                    <bpws:links>\n"
                + "                                    <bpws:link\n"
                + "                                    name=\"GroupStartToLog\" tibex:linkType=\"SUCCESS\"/>\n"
                + "                                    <bpws:link\n"
                + "                                    name=\"LogToGroupEnd\" tibex:linkType=\"SUCCESS\"/>\n"
                + "                                    </bpws:links>\n"
                + "                                    <bpws:assign\n"
                + "                                    name=\"GroupStart\"\n"
                + "                                    tibex:group=\"groupStart\"\n"
                + "                                    tibex:xpdlId=\"6d3488e2-3983-4881-ae7c-84c50d690ba1\" validate=\"no\">\n"
                + "                                    <bpws:sources>\n"
                + "                                    <bpws:source linkName=\"GroupStartToLog\"/>\n"
                + "                                    </bpws:sources>\n"
                + "                                    <bpws:copy>\n"
                + "                                    <bpws:from expressionLanguage=\"urn:oasis:names:tc:wsbpel:2.0:sublang:xpath2.0\"/>\n"
                + "                                    <bpws:to variable=\"currentElement\"/>\n"
                + "                                    </bpws:copy>\n"
                + "                                    </bpws:assign>\n"
                + "                                    <bpws:empty\n"
                + "                                    name=\"GroupEnd\"\n"
                + "                                    tibex:group=\"groupEnd\" tibex:xpdlId=\"986146e9-2f41-4d1a-bc67-1734edb9d5df\">\n"
                + "                                    <bpws:targets>\n"
                + "                                    <bpws:target linkName=\"LogToGroupEnd\"/>\n"
                + "                                    </bpws:targets>\n"
                + "                                    </bpws:empty>\n"
                + "                                    <bpws:extensionActivity>\n"
                + "\n"
                + "                                    <tibex:activityExtension\n"
                + "                                    inputVariable=\"Log-input\"\n"
                + "                                    name=\"Log\"\n"
                + "                                    tibex:xpdlId=\"f708c7e7-14b9-4d9a-b8f2-0b1675c1af71\" xmlns:tibex=\"http://www.tibco.com/bpel/2007/extensions\">\n"
                + "                                    <bpws:targets>\n"
                + "\n"
                + "                                    <bpws:target linkName=\"GroupStartToLog\"/>\n"
                + "                                    </bpws:targets>\n"
                + "                                    <bpws:sources>\n"
                + "\n"
                + "                                    <bpws:source linkName=\"LogToGroupEnd\"/>\n"
                + "                                    </bpws:sources>\n"
                + "                                    <tibex:inputBindings>\n"
                + "\n"
                + "                                    <tibex:inputBinding\n"
                + "                                    expression=\"&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?> &lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:tns=&quot;http://www.tibco.com/pe/WriteToLogActivitySchema&quot; version=&quot;2.0&quot;> &lt;xsl:template name=&quot;Log-input&quot; match=&quot;/&quot;> &lt;tns:ActivityInput/>&lt;/xsl:template> &lt;/xsl:stylesheet>\" expressionLanguage=\"urn:oasis:names:tc:wsbpel:2.0:sublang:xslt1.0\"/>\n"
                + "                                    </tibex:inputBindings>\n"
                + "                                    <tibex:config>\n"
                + "\n"
                + "                                    <bwext:BWActivity\n"
                + "                                    activityTypeID=\"bw.generalactivities.log\"\n"
                + "                                    version=\"6.0.0.001\"\n"
                + "                                    xmlns:activityconfig=\"http://tns.tibco.com/bw/model/activityconfig\"\n"
                + "                                    xmlns:bwext=\"http://tns.tibco.com/bw/model/core/bwext\"\n"
                + "                                    xmlns:generalactivities=\"http://ns.tibco.com/bw/palette/generalactivities\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
                + "                                    <activityConfig>\n"
                + "\n"
                + "                                    <properties\n"
                + "                                    name=\"config\" xsi:type=\"activityconfig:EMFProperty\">\n"
                + "\n"
                + "                                    <type href=\"http://ns.tibco.com/bw/palette/generalactivities#//Log\"/>\n"
                + "\n"
                + "                                    <value\n"
                + "                                    controlBy=\"Application\"\n"
                + "                                    role=\"Info\"\n"
                + "                                    suppressJobInfo=\"true\" xsi:type=\"generalactivities:Log\"/>\n"
                + "                                    </properties>\n"
                + "                                    </activityConfig>\n"
                + "                                    </bwext:BWActivity>\n"
                + "                                    </tibex:config>\n"
                + "                                    </tibex:activityExtension>\n"
                + "                                    </bpws:extensionActivity>\n"
                + "                                    </bpws:flow>\n"
                + "                                    </bpws:scope>\n"
                + "                                    </bpws:forEach>\n"
                + "                                    </bpws:sequence>\n"
                + "                                </bpws:scope>\n"
                + "                            </bpws:flow>\n"
                + "                        </bpws:scope>\n"
                + "                    </bpws:forEach>\n"
                + "                </bpws:sequence>\n"
                + "            </bpws:scope>\n"
                + "        </bpws:flow>\n"
                + "    </bpws:scope>\n"
                + "</bpws:process>");

    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Test
    public void testValidate() {

            System.out.println("testValidate");
            UnneededGroupCheck instance = new UnneededGroupCheck();
            UnneededGroupCheck spyInstance = Mockito.spy(instance);
            doNothing().when(spyInstance).reportIssueOnFile(any(), anyInt());
            spyInstance.validate(source);
            Mockito.verify(spyInstance, times(1)).reportIssueOnFile(anyString(), anyInt());



    }
}
