//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 12:10:07 PM CET 
//


package com.tibco.xmlns.extarchetype.validation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomRule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tibco.com/xmlns/extarchetype/validation}AbstractRule">
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([^dwitf].*|[dwitf]|d[^e].*|de|de[^f].*|def|def[^a].*|defa|defa[^u].*|defau|defau[^l].*|defaul|defaul[^t].*|default.+|w[^a].*|wa|wa[^r].*|war|war[^n].*|warn|warn[^i].*|warni|warni[^n].*|warnin|warnin[^g].*|warning.+|i[^n].*|in|in[^f].*|inf|inf[^o].*|info.+|t[^o].*|to|to[^k].*|tok|tok[^e].*|toke|toke[^n].*|token.+|f[^i].*|fi|fi[^x].*|fix|fix[^e].*|fixe|fixed.+)"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomRule")
public class CustomRule
    extends AbstractRule
{

    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
